#!/bin/sh
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit 1
fi

head="/usr/local/share/defender/default/head6.rules"
tail="/usr/local/share/defender/default/tail6.rules"
ind6="/usr/local/share/defender/block/individual6.list"
ind6b=$ind6."bak"
opfile="/usr/local/share/defender/before6.rules"
livefile="/etc/ufw/before6.rules"
webfile="/var/www/===server address===/before6.rules"

if [ "$#" -lt 1 ]; then
   echo "IP address to block must be specified"
   exit 1
fi

echo "$1" >> $ind6
echo "====> $1 added to block list"

if [ "$#" -gt 1 ]; then
   if [ "$2" ]; then
      cp $ind6 $ind6b
      sort $ind6b | uniq > $ind6
      awk 'NF' $ind6 > $ind6
      
      cp $head $opfile
      echo "#### block IP6 addresses " >> $opfile
      while IFS= read -r line
        do
           echo "-A ufw6-before-input -s $line -j DROP" >> $opfile
        done < $ind6
      echo "#### end of block IP6 addresses " >> $opfile
      cat $tail >> $opfile
      cp $opfile $livefile
      cp $opfile $webfile
      ufw reload
      echo "=====> ufw reloaded"
   fi
fi


